services:
  android-emulator:
    image: budtmo/docker-android:emulator_14.0
    container_name: android-emulator
    privileged: true
    devices:
      - /dev/kvm:/dev/kvm
    ports:
      - "6080:6080"
      - "4723:4723"
      - "5554:5554"
      - "5555:5555"
    environment:
      - DEVICE=Samsung Galaxy S10
      - APPIUM=true
      - WEB_VNC=true
    volumes:
      - ./apps:/apps
    networks:
      - test-network

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-runner
    volumes:
      - .:/workspace
    environment:
      - APPIUM_HOST=android-emulator
      - APPIUM_PORT=4723
      - ANDROID_DEVICE_NAME=emulator-5554
    depends_on:
      - android-emulator
    networks:
      - test-network
    command: >
      bash -c "
        echo 'Waiting for Android emulator to be ready...' &&
        while [ \"\$(docker exec android-emulator cat device_status)\" != \"READY\" ]; do
          echo 'Emulator status: '\$(docker exec android-emulator cat device_status) &&
          sleep 10
        done &&
        echo 'Emulator is READY! Installing APK...' &&
        adb connect android-emulator:5555 &&
        adb install /apps/Android.SauceLabs.Mobile.Sample.app.2.7.1.apk &&
        echo 'Running tests...' &&
        mvn clean test
      "

networks:
  test-network: