name: Mobile Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mobile-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download APK
        run: |
          mkdir -p apps
          wget -O apps/Android.SauceLabs.Mobile.Sample.app.2.7.1.apk \
          "https://github.com/saucelabs/sample-app-mobile/releases/download/2.7.1/Android.SauceLabs.Mobile.Sample.app.2.7.1.apk"

      - name: Run tests
        run: docker compose up --build --abort-on-container-exit

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: target/cucumber-reports/
